/**
 * Popular Ollama model names.
 */
export enum EOllamaModel {
	CODELLAMA = "codellama",
	CODESTRAL = "codestral",
	CUSTOM = "custom",
	DEEPSEEK_R1 = "deepseek-r1",
	DEEPSEEK_V4_FLASH_CLOUD = "deepseek-v4-flash:cloud",
	DEEPSEEK_V4_PRO_CLOUD = "deepseek-v4-pro:cloud",
	DEVSTRAL = "devstral",
	GEMMA3 = "gemma3",
	GEMMA3N = "gemma3n",
	GEMMA4 = "gemma4",
	GLM_5_1_CLOUD = "glm-5.1:cloud",
	GPT_OSS = "gpt-oss",
	GRANITE4_1 = "granite4.1",
	KIMI_K2_6_CLOUD = "kimi-k2.6:cloud",
	LAGUNA_XS_2 = "laguna-xs.2",
	LLAMA3_1 = "llama3.1",
	LLAMA3_2 = "llama3.2",
	LLAMA3_2_VISION = "llama3.2-vision",
	LLAMA3_3 = "llama3.3",
	LLAMA4 = "llama4",
	MINIMAX_M2_7_CLOUD = "minimax-m2.7:cloud",
	MISTRAL = "mistral",
	MISTRAL_NEMO = "mistral-nemo",
	MISTRAL_SMALL3_2 = "mistral-small3.2",
	MIXTRAL = "mixtral",
	NEMOTRON3 = "nemotron3",
	PHI4 = "phi4",
	QWEN2_5_CODER = "qwen2.5-coder",
	QWEN3 = "qwen3",
	QWEN3_5 = "qwen3.5",
	QWEN3_6 = "qwen3.6",
	QWEN3_CODER = "qwen3-coder",
	QWEN3_CODER_NEXT = "qwen3-coder-next",
}
